name: technician
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.17+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  get: ^4.6.6
  flutter_bloc: ^9.1.1
  lottie: ^3.1.2
  dio: ^5.7.0
  get_it: ^9.1.1
  equatable: ^2.0.5
  internet_connection_checker: ^3.0.1
  url_launcher: ^6.3.0
  modal_bottom_sheet: ^3.0.0
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  app_links: ^6.4.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  table_calendar: ^3.1.2
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  saver_gallery: ^4.1.0
  syncfusion_flutter_signaturepad: ^28.2.12
  pdf: ^3.11.1
  printing: ^5.13.3
  google_maps_flutter: any
  http: any
  flutter_widget_from_html: ^0.16.1
  flutter_launcher_icons: ^0.14.1
  geolocator: ^11.0.0
  flutter_swipe_button: ^2.1.3
  swipeable_button_flutter: ^0.0.3
  package_info_plus: ^8.3.0
#  chewie: ^1.8.6
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  timelines: ^0.1.0
  flutter_timeline: ^0.3.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  file_picker: ^10.3.7
  flutter_slidable: ^3.1.2
  mobile_scanner: ^6.0.7
  new_version_plus: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 700
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 700
    - family: Hacen Tunisia
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
